### ISSUE TITLE
Miui国际版rom的市场里是搜不到的。

### ISSUE THREAD

**Issue by xiamubobby** [sorcererXW/SorceryIconPack#3]
因此就是web里能搜到但Miui系统里装不了。是不是需要声明一下支持些什么rom之类的？机：小米 5s plus。已解锁。系统是Global Developwr Firmware。就是在英文谷歌下搜索xiaomi 5s plus rom download之后出来的那个官方页面里的rom。（miui版本同为v8）

**Comment by xmlxin** [comment]
没有提交XposedInstaller类

**Comment by sorcererXW** [comment]
@xiamubobby 由于是收费主题, 只支持国内版的MIUI主题商店
