### ISSUE TITLE
Pixel 启动器的缓存具体是怎么更新的呢

### ISSUE THREAD

**Issue by ZeppLu** [sorcererXW/SorceryIconPack#5]
如题，因为对这个好奇所以扒了一下源码，然后发现应该是 `com.sorcerer.sorcery.iconpack.apply.database.pixel.PixelApplySingleInstanceProgressActivity` 里面的，但 `iconpack` 下面并没有 `apply` 文件夹。

所以这部分的实现是故意不放出来吗？反正都 GPL 了，也没啥好顾忌的吧。

**Comment by sorcererxw** [comment]
root更新缓存这部分暂时没有完善, 暂时还不想开源
具体方式其实就是修复launcher的database目录下的图标数据库

**Comment by ZeppLu** [comment]
原理跟我想象的差不多，不过我想扒源码其实是因为一个奇怪的 bug：每次我打开过即刻 app 后，它的图标都会变回去。不过既然这个图标包是直接更改 database 的，那就应该不关这个图标包的事了，也许是即刻调用了什么方法让 launcher 更新了数据库。
